const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
    const browser = await chromium.launch({ channel: 'msedge', headless: true });
    try {
        const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        const makeNode = (id, x, type = 'idea') => ({ id, x, y: 50, type, shape: 'rectangle', title: id, note: '', level: 1, status: 'idea', stage: '', tags: '', media: [] });
        let document = { nodes: [makeNode('A', 30, 'shape'), makeNode('B', 380)], edges: [{ a: 'A', b: 'B' }], strokes: [[{ x: 100, y: 350 }, { x: 200, y: 350 }], [{ x: 300, y: 350 }, { x: 400, y: 350 }]] };
        let revision = 1;
        // Browser tests use a private in-memory API, leaving the user's map untouched.
        await page.route('**/api/map', async route => {
            if (route.request().method() === 'PUT') {
                const payload = route.request().postDataJSON();
                assert.equal(payload.revision, revision);
                document = payload.document;
                revision++;
                await route.fulfill({ json: { revision } });
            } else await route.fulfill({ json: { revision, document } });
        });
        await page.goto('http://127.0.0.1:8000');
        await page.locator('.node').first().waitFor();
        assert.equal(await page.locator('.edge').evaluate(el => getComputedStyle(el).stroke), 'rgb(48, 59, 56)');
        assert.equal(await page.locator('.edge').getAttribute('marker-end'), 'url(#arrow-normal)');
        const light = await page.locator('body').evaluate(el => getComputedStyle(el).color);
        await page.locator('#theme').click();
        assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
        const dark = await page.locator('body').evaluate(el => getComputedStyle(el).color);
        assert.notEqual(dark, light);
        const line = await page.locator('.edge').evaluate(el => getComputedStyle(el).stroke);
        assert.equal(line, 'rgb(240, 244, 241)');
        await page.locator('[data-id="A"]').click({ button: 'right' });
        await page.getByRole('menuitem', { name: 'Форма: Треугольник', exact: true }).click();
        assert.ok((await page.locator('[data-id="A"]').getAttribute('class')).includes('shape-triangle'));
        await page.locator('#undo').click();
        assert.ok((await page.locator('[data-id="A"]').getAttribute('class')).includes('shape-rectangle'));
        const canvas = await page.locator('#canvas').boundingBox();
        await page.mouse.click(canvas.x + 30, canvas.y + 30, { button: 'right' });
        await page.getByRole('menuitem', { name: 'Создать: Ромб', exact: true }).click();
        assert.equal(await page.locator('.shape-diamond').count(), 1);
        const edgePoint = await page.locator('.edge-hit').evaluate(el => {
            const point = el.getPointAtLength(el.getTotalLength() / 2);
            const screen = new DOMPoint(point.x, point.y).matrixTransform(el.getScreenCTM());
            return { x: screen.x, y: screen.y };
        });
        await page.mouse.click(edgePoint.x, edgePoint.y);
        await page.locator('#edgePriority').selectOption('important');
        assert.equal(await page.locator('.edge').evaluate(el => getComputedStyle(el).stroke), 'rgb(255, 192, 92)');
        await page.locator('#edgeDirection').selectOption('both');
        assert.equal(await page.locator('.edge').getAttribute('marker-start'), 'url(#arrow-important)');
        assert.equal(await page.locator('.edge').getAttribute('marker-end'), 'url(#arrow-important)');
        await page.locator('#edgeDirection').selectOption('none');
        assert.equal(await page.locator('.edge').getAttribute('marker-start'), null);
        assert.equal(await page.locator('.edge').getAttribute('marker-end'), null);
        await page.locator('#edgeDirection').selectOption('forward');
        await page.locator('#edgePriority').selectOption('high');
        assert.equal(await page.locator('.edge').evaluate(el => getComputedStyle(el).stroke), 'rgb(255, 119, 119)');
        assert.equal(await page.locator('#arrow-high path').evaluate(el => getComputedStyle(el).fill), 'rgb(255, 119, 119)');
        await page.locator('#edgeDirection').selectOption('backward');
        assert.equal(await page.locator('.edge').getAttribute('marker-start'), 'url(#arrow-high)');
        assert.equal(await page.locator('.edge').getAttribute('marker-end'), null);
        await page.locator('#undo').click();
        assert.equal(await page.locator('.edge').getAttribute('marker-end'), 'url(#arrow-high)');
        await page.locator('#redo').click();
        assert.equal(await page.locator('.edge').getAttribute('marker-start'), 'url(#arrow-high)');
        await page.locator('#theme').click();
        assert.equal(await page.locator('.edge').evaluate(el => getComputedStyle(el).stroke), 'rgb(195, 50, 50)');
        await page.locator('#theme').click();
        await page.mouse.click(edgePoint.x, edgePoint.y, { button: 'right' });
        await page.getByRole('menuitem', { name: 'Удалить связь', exact: true }).click();
        assert.equal(await page.locator('.edge-hit').count(), 0);
        await page.locator('#undo').click();
        assert.equal(await page.locator('.edge-hit').count(), 1);
        const stroke = await page.locator('.drawing-stroke').first().boundingBox();
        await page.locator('#erase').click();
        await page.mouse.click(stroke.x + stroke.width / 2, stroke.y);
        assert.equal(await page.locator('.drawing-stroke').count(), 1);
        await page.locator('#undo').click();
        assert.equal(await page.locator('.drawing-stroke').count(), 2);
        await page.locator('#redo').click();
        assert.equal(await page.locator('.drawing-stroke').count(), 1);
        await page.keyboard.press('Escape');
        await page.mouse.move(canvas.x + 50, canvas.y + 40);
        await page.mouse.wheel(0, -100);
        await page.waitForFunction(() => document.getElementById('zoom').textContent !== '100%');
        assert.notEqual(await page.locator('#zoom').textContent(), '100%');
        await page.waitForFunction(() => document.getElementById('saveState').textContent === '● Сохранено');
        assert.equal(document.strokes.length, 1);
        assert.ok(document.nodes.some(n => n.shape === 'diamond'));
        assert.equal(document.edges[0].priority, 'high');
        assert.equal(document.edges[0].direction, 'backward');
        await page.reload();
        await page.locator('.node').first().waitFor();
        assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
        assert.equal(await page.locator('.shape-diamond').count(), 1);
        assert.equal(await page.locator('.drawing-stroke').count(), 1);
        assert.equal(await page.locator('.edge').getAttribute('marker-start'), 'url(#arrow-high)');
        assert.equal(await page.locator('.edge').evaluate(el => getComputedStyle(el).stroke), 'rgb(255, 119, 119)');
        const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#context').click()]);
        const stream = await download.createReadStream();
        const chunks = [];
        for await (const chunk of stream) chunks.push(chunk);
        const markdown = Buffer.concat(chunks).toString('utf8');
        assert.match(markdown, /B → A · Основная идея: B · приоритет: Высокий/);
        const deletePoint = await page.locator('.edge-hit').evaluate(el => {
            const p=el.getPointAtLength(el.getTotalLength()/2);
            const point=new DOMPoint(p.x,p.y).matrixTransform(el.getScreenCTM());
            return {x:point.x,y:point.y};
        });
        await page.mouse.click(deletePoint.x,deletePoint.y);
        await page.keyboard.press('Delete');
        assert.equal(await page.locator('.edge-hit').count(),0);
        await page.keyboard.press('Control+z');
        assert.equal(await page.locator('.edge-hit').count(),1);
        await page.locator('[data-id="A"]').click();
        await page.keyboard.press('Delete');
        assert.equal(await page.locator('[data-id="A"]').count(),0);
        assert.equal(await page.locator('.edge-hit').count(),0);
        await page.keyboard.press('Control+z');
        assert.equal(await page.locator('[data-id="A"]').count(),1);
        assert.equal(await page.locator('.edge-hit').count(),1);
        await page.locator('[data-id="B"]').click();
        await page.locator('#title').fill('Текст');
        await page.locator('#title').press('Home');
        await page.locator('#title').press('Delete');
        assert.equal(await page.locator('#title').inputValue(),'екст');
        assert.equal(await page.locator('[data-id="B"]').count(),1);
        await page.locator('[data-id="B"]').click();
        await page.keyboard.press('Delete');
        assert.equal(await page.locator('[data-id="B"]').count(),0);
        await page.keyboard.press('Control+z');
        assert.equal(await page.locator('[data-id="B"]').count(),1);
        assert.equal(await page.locator('.edge-hit').count(),1);
        await page.keyboard.press('Control+Shift+z');
        assert.equal(await page.locator('[data-id="B"]').count(),0);
        await page.waitForFunction(()=>document.getElementById('saveState').textContent==='● Сохранено');
        assert.ok(!document.nodes.some(node=>node.id==='B'));
        assert.equal(await page.locator('#canvas .hint,#canvas .boardLabel').count(),0);
        assert.equal(await page.locator('#canvas').evaluate(el=>getComputedStyle(el).userSelect),'none');
        // Pan through both former labels, including beyond the canvas boundary.
        for(const bottom of [false,true]){
            await page.locator('#home').click();
            const area=await page.locator('#canvas').boundingBox();
            const before=await page.locator('#world').evaluate(el=>{const m=new DOMMatrix(getComputedStyle(el).transform);return{x:m.e,y:m.f};});
            const start={x:area.x+10,y:bottom?area.y+area.height-30:area.y+30};
            await page.mouse.move(start.x,start.y);
            await page.mouse.down();
            await page.mouse.move(start.x+160,start.y+40,{steps:12});
            await page.mouse.up();
            const after=await page.locator('#world').evaluate(el=>{const m=new DOMMatrix(getComputedStyle(el).transform);return{x:m.e,y:m.f};});
            assert.equal(after.x-before.x,160);
            assert.equal(after.y-before.y,40);
            assert.equal(await page.evaluate(()=>window.getSelection().toString()),'');
        }
        await page.locator('#home').click();
        await page.locator('[data-id="A"]').click();
        await page.locator('#note').fill('Текст заметки');
        await page.locator('#note').press('Control+a');
        assert.equal(await page.locator('#note').evaluate(el=>el.value.slice(el.selectionStart,el.selectionEnd)),'Текст заметки');
        assert.deepEqual(errors, []);
        console.log('Browser OK: editor regressions, edge priorities/colors/arrows, Undo/Redo, theme adaptation and save/reload; user data untouched');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
